export const FETCH_LATEST_RESULT_START = 'FETCH_LATEST_RESULT_START';
export const FETCH_LATEST_RESULT_SUCCESS = 'FETCH_LATEST_RESULT_SUCCESS';
export const FETCH_LATEST_RESULT_FAIL = 'FETCH_LATEST_RESULT_FAIL';