export const FETCH_LATEST_RESULT_START = 'FETCH_LATEST_RESULT_START';
export const FETCH_LATEST_RESULT_SUCCESS = 'FETCH_LATEST_RESULT_SUCCESS';
export const FETCH_LATEST_RESULT_FAIL = 'FETCH_LATEST_RESULT_FAIL';

export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';